# Generated by Django 6.0 on 2026-06-22 17:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnologiaAssistiva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('comunicacao', 'Comunicação'), ('sensorial', 'Sensorial'), ('motor', 'Motor'), ('cognitivo', 'Cognitivo'), ('social', 'Social')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('exemplos_uso', models.TextField(blank=True, null=True)),
                ('avaliacao_media', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tecnologia Assistiva',
                'verbose_name_plural': 'Tecnologias Assistivas',
                'db_table': 'tecnologia_assistiva',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nivel_suporte', models.IntegerField(choices=[(1, 'Nível 1 - Suporte Leve'), (2, 'Nível 2 - Suporte Moderado'), (3, 'Nível 3 - Suporte Intensivo')])),
                ('turma', models.CharField(blank=True, max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='estudantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
                'db_table': 'estudante',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PEI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('estrategias', models.TextField(blank=True, null=True)),
                ('recursos', models.TextField(blank=True, null=True)),
                ('versao', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='peis', to='telas.estudante')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='peis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PEI',
                'verbose_name_plural': 'PEIs',
                'db_table': 'pei',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilTEA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comunicacao', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil_sensorial', models.CharField(blank=True, max_length=100, null=True)),
                ('habilidade_motora', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil_cognitivo', models.CharField(blank=True, max_length=100, null=True)),
                ('desafios', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estudante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_tea', to='telas.estudante')),
            ],
            options={
                'verbose_name': 'Perfil TEA',
                'verbose_name_plural': 'Perfis TEA',
                'db_table': 'perfil_tea',
            },
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parametros_entrada', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('gerada', 'Gerada'), ('visualizada', 'Visualizada'), ('arquivada', 'Arquivada')], default='gerada', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recomendacoes', to='telas.estudante')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recomendacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
                'db_table': 'recomendacao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RecomendacaoTA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('posicao_ranking', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('recomendacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_ta', to='telas.recomendacao')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recomendacoes', to='telas.tecnologiaassistiva')),
            ],
            options={
                'verbose_name': 'Recomendação TA',
                'verbose_name_plural': 'Recomendações TA',
                'db_table': 'recomendacao_ta',
                'ordering': ['posicao_ranking'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avaliacao', models.CharField(choices=[('aceita', 'Aceita'), ('a_testar', 'A Testar'), ('rejeitada', 'Rejeitada')], max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('recomendacao_ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='telas.recomendacaota')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedback',
            },
        ),
    ]
