# Generated by Django 6.0 on 2026-06-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologiaassistiva',
            name='como_fazer',
            field=models.TextField(blank=True, help_text='Passo a passo de como criar/fazer', null=True),
        ),
        migrations.AddField(
            model_name='tecnologiaassistiva',
            name='como_usar',
            field=models.TextField(blank=True, help_text='Como utilizar a tecnologia', null=True),
        ),
        migrations.AddField(
            model_name='tecnologiaassistiva',
            name='materiais',
            field=models.TextField(blank=True, help_text='Materiais necessários para criar/adaptar', null=True),
        ),
        migrations.AddField(
            model_name='tecnologiaassistiva',
            name='para_que_serve',
            field=models.TextField(blank=True, help_text='Para que serve esta tecnologia', null=True),
        ),
        migrations.AlterField(
            model_name='tecnologiaassistiva',
            name='categoria',
            field=models.CharField(choices=[('comunicacao', 'Comunicação'), ('regulacao_sensorial', 'Regulação Sensorial'), ('motor', 'Motor'), ('cognitivo', 'Cognitivo'), ('interacao_social', 'Interação Social'), ('estruturacao', 'Estruturação')], max_length=50),
        ),
    ]
