# Generated by Django 6.0 on 2026-06-24 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0002_tecnologiaassistiva_como_fazer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pei',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peis', to='telas.estudante'),
        ),
        migrations.AlterField(
            model_name='pei',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='telas.estudante'),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recomendacaota',
            name='ta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='telas.tecnologiaassistiva'),
        ),
    ]
