# Generated by Django 6.0 on 2026-07-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0003_alter_feedback_professor_alter_pei_estudante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologiaassistiva',
            name='criada_por_ia',
            field=models.BooleanField(default=False, help_text='Indica se foi criada pela IA'),
        ),
    ]
