# Generated by Django 6.0 on 2026-07-13 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0004_tecnologiaassistiva_criada_por_ia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSeguranca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('falha_login', 'Falha de Login'), ('2fa', '2FA'), ('cadastro', 'Cadastro'), ('alteracao_senha', 'Alteração de Senha'), ('recuperacao_senha', 'Recuperação de Senha'), ('acesso_negado', 'Acesso Negado'), ('ataque', 'Ataque Detectado'), ('honeypot', 'Honeypot'), ('admin', 'Ação Administrativa'), ('exclusao', 'Exclusão'), ('edicao', 'Edição'), ('criacao', 'Criação')], max_length=50)),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('warning', 'Aviso'), ('error', 'Erro'), ('critical', 'Crítico')], default='info', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('dados_extra', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_seguranca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Segurança',
                'verbose_name_plural': 'Logs de Segurança',
                'db_table': 'log_seguranca',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tipo', 'criado_em'], name='log_seguran_tipo_00b455_idx'), models.Index(fields=['usuario', 'criado_em'], name='log_seguran_usuario_af0d28_idx'), models.Index(fields=['ip', 'criado_em'], name='log_seguran_ip_a11edb_idx'), models.Index(fields=['nivel'], name='log_seguran_nivel_d7a58b_idx')],
            },
        ),
    ]
