# Generated by Django 6.0 on 2026-07-13 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0005_logseguranca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermosUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('tipo', models.CharField(choices=[('termos_uso', 'Termos de Uso'), ('politica_privacidade', 'Política de Privacidade'), ('consentimento_menor', 'Consentimento para Menores')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Termo de Uso',
                'verbose_name_plural': 'Termos de Uso',
                'db_table': 'termos_uso',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AceiteTermos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('data_aceite', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites_termos', to=settings.AUTH_USER_MODEL)),
                ('termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telas.termosuso')),
            ],
            options={
                'verbose_name': 'Aceite de Termo',
                'verbose_name_plural': 'Aceites de Termos',
                'db_table': 'aceite_termos',
            },
        ),
    ]
