# Generated by Django 6.0 on 2026-07-13 22:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telas', '0006_termosuso_aceitetermos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, '1 estrelas'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_tecnologias', to=settings.AUTH_USER_MODEL)),
                ('tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='telas.tecnologiaassistiva')),
            ],
            options={
                'verbose_name': 'Avaliação de Tecnologia',
                'verbose_name_plural': 'Avaliações de Tecnologias',
                'db_table': 'avaliacao_tecnologia',
                'ordering': ['-criado_em'],
                'unique_together': {('tecnologia', 'professor')},
            },
        ),
    ]
