# Generated by Django 6.0 on 2026-06-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('professor', 'Professor'), ('coordenador', 'Coordenador'), ('especialista', 'Especialista')], max_length=20),
        ),
    ]
